<?php
/**
 * @file
 * Code for the ddc_article feature.
 */

use \Drupal\ddc_article\EntityWrapper\Node\ArticleWrapper;

include_once 'ddc_article.features.inc';

/**
 * Implements hook_permission().
 */
function ddc_article_permission() {
  return array(
    'access members articles' => array(
      'title' => t('Access members-only Articles'),
      'description' => t('Access Articles which are reserved for members-only.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ddc_article_form_article_node_form_alter(&$form, &$form_state, $form_id) {
  // Hide the general availability date field if the highlighted box is not checked.
  $form['field_available_date']['#states'] = array(
    // Only show the field when the Highlighted field is checked.
    'visible' => array(
      ':input[name="field_highlight"]' => array('checked' => TRUE),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function ddc_article_node_view($node, $view_mode, $langcode) {
  // We're only working with Articles.
  if ($node->type != 'article') {
    return;
  }

  // Don't restrict users who have the 'access members articles' permission.
  if (user_access('access members articles')) {
    return;
  }

  // Wrap the node.
  $wrapper = new ArticleWrapper($node);
  // Check if the node should be for members-only.
  if ($wrapper->isMembersOnly()) {
    // It is, and we don't have the permission, so replace the body content
    // with a signup call-to-action.
    $signup = l(t('Sign up now'), 'user/register', array(
      'query' => drupal_get_destination(),
      'attributes' => array(
        'class' => array('btn', 'btn-primary'),
      ),
    ));
    $node->content['body'] = array(
      '#type' => 'markup',
      '#markup' => t('This content is only available to members. !signup', array(
        '!signup' => $signup,
      )),
    );
  }
}